# These are supported funding model platforms

github: [abdullahhafizh, Hi-Fiez] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: abdullahhafizh # Replace with a single Patreon username
open_collective: abdullahhafizh # Replace with a single Open Collective username
ko_fi: abdullahhafizh # Replace with a single Ko-fi username
tidelift: abdullahhafizh/laravel-curl-helper # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: hifiez-soft # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: abdullahhafizh # Replace with a single Liberapay username
issuehunt: abdullahhafizh # Replace with a single IssueHunt username
otechie: abdullahhafizh # Replace with a single Otechie us#ername
#custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
